CREATE DATABASE IF NOT EXISTS movie_reviews;
USE movie_reviews;

CREATE TABLE IF NOT EXISTS reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  movie_title VARCHAR(255) NOT NULL,
  rating DECIMAL(3,1) NOT NULL,
  review TEXT NOT NULL,
  submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
